services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3
        hostname: my-rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=user
          - RABBITMQ_DEFAULT_PASS=123456
        ports:
         - 5672:5672